### ISSUE TITLE
error with  'cls.selectors'

### ISSUE THREAD

**Issue by reagle** [admhlt/SublimeLinter-contrib-vale#3]
I just installed it and got the following errors using value 1.7.0 .

```
SublimeLinter: ERROR:
=====================

vale: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

vale: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

vale disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```

**Comment by dylan-k** [comment]
Looking at similar occurrences of this error with other packages, the advice seems to be to upgrade to the latest version. Since there hasn't been a new version of this package since its release 2 years ago, I'm guessing that there was a change to SublimeLinter that causes this version of SublimeLinter-contrib-vale to have the errors. 

I made a fork that addresses the issue. https://github.com/dylan-k/SublimeLinter-contrib-vale

**Comment by craigmac** [comment]
@adamhollett @dylan-k are you still interested in maintaining this? If not I'm going to fork it and create a PR with SublimeLinter because as of a couple hours ago they were pointing to the wrong repo URL, and now that that has been fixed [here](https://github.com/SublimeLinter/package_control_channel/commit/9df0ebf970551c8c80614bce0a0a35c10263e8b6) it seems to only be installing the tagged 1.0.0 release which is missing the changes required to work that are on HEAD.

**Comment by dylan-k** [comment]
I no longer maintain this, but please feel free to use it however needed.

**Comment by kaste** [comment]
Transfer it to @craigmac or into the SublimeLinter org

**Comment by kaste** [comment]
Actually @furkanayhan has the best version currently https://github.com/furkanayhan/SublimeLinter-contrib-vale so fork or pull that one maybe.

**Comment by tim-hilde** [comment]
I just found out about this and am still getting the error. Would love to see this resolved

**Comment by adamhollett** [comment]
Yeah, sorry all, I am not actively maintaining this repo. Thanks for making the forks and I'll accept PRs but I don't use Sublime or Vale any more. If there's a consensus on who might be a better maintainer I'm happy to transfer ownership.

**Comment by kaste** [comment]
Wait a day or so if others respond. You can transfer it to me and I will add it to the org of course.

**Comment by kaste** [comment]
Shipping v1.0.1 now
